---
--- Generated by Luanalysis
--- Created by ouyang.
--- DateTime: 2023/9/2 20:00
---
-- 比较线程标示与锁中的标示是否一致
if(redis.call('get', KEYS[1]) ==  ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0